.gitignore

Add two exceptions to the .* for travis and gitignore, fixes warnings in IDEs.

Add 2 exceptions to gitignore for .travis and .gitignore.

---

docs/using-docker.md

Current loading snomed link in using-docker documentation is broken
Fixed the reference for it to go to
https://github.com/IHTSDO/snowstorm/blob/master/docs/loading-snomed.md
instead of 
https://github.com/IHTSDO/snowstorm/blob/master/docs/docs/loading-snomed.md

Fix loading-snomed doc link

---

src/main/java/org/snomed/snowstorm/config/Config.java
src/main/resources/application.properties

Using AWS ElasticSearch Service posed some issues to us. Using IAM Users for our domain access policy, we were unable to connect to the elasticsearch service. This required requests to be signed. 
https://docs.aws.amazon.com/elasticsearch-service/latest/developerguide/es-request-signing.html
this seems like a nice feature to have, and it is quite standard to use IAM access policies for AWS services. 
Using default providers, the config for region, accessKeyId & accessKeySecret can be injected with environment variables.
AWS_REGION
AWS_ACCESS_KEY_ID
AWS_SECRET_KEY

added config and dependencies for request signing with aws credentials

---

docs/fhir-requests.http

I have updated this file to include /fhir in the baseUrl. This is more consistent with the specification and other implementations.

Updated the baseUrl

---

src/main/java/org/snomed/snowstorm/core/data/services/ConceptUpdateHelper.java
src/main/java/org/snomed/snowstorm/core/util/SetUtils.java
src/test/java/org/snomed/snowstorm/core/data/services/BranchMergeServiceTest.java

Merging of the historical associations of a concept or description can happen either by saving a new version of a concept through the API or by merging two branches together. When merging two branches we were finding that duplicate records were created because two refset members with the same refset id and association target existed on both sides of the merge. We try to favour the released and active records so a comparator is now used for this.

Fix MAINT-1322, Rewrite of historical association merge.

---

src/main/java/org/snomed/snowstorm/core/data/domain/Relationship.java
src/main/java/org/snomed/snowstorm/core/data/services/AxiomConversionService.java
src/main/java/org/snomed/snowstorm/core/data/services/SemanticIndexUpdateService.java
src/main/java/org/snomed/snowstorm/core/data/services/TraceabilityLogService.java
src/test/java/org/snomed/snowstorm/core/data/services/ConceptServiceTest.java

CDI-29 is concerned with adding support for importing concrete Relationships. 
I have made the following code changes in order for concrete Relationships to be imported that have been converted from Axioms.
**Note:-** This code is related to snomed-owl-toolkit@feature/CDI-29.

CDI-29 -- Add support for importing concrete Relationships converted from Axioms

---

src/main/java/org/snomed/snowstorm/core/data/domain/ComponentType.java
src/main/java/org/snomed/snowstorm/core/data/services/ConceptService.java
src/main/java/org/snomed/snowstorm/core/data/services/pojo/ConceptHistory.java
src/main/java/org/snomed/snowstorm/rest/ConceptController.java
src/test/java/org/snomed/snowstorm/rest/ConceptControllerTest.java

BROWSE-241 is concerned with updating Snowstorm's API to include a method for returning the history of a Concept.

BROWSE-241 -- View history of a Concept

---

src/main/java/org/snomed/snowstorm/fhir/exceptions/MissingParameterException.java
src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProvider.java

The reason for : `@ResourceParam String rawBody` was because there isn't a nice way to encapsulate the POST body which is sent up so after doing some research, this is a work around which under a POST operation, contains the body then a simple cast can occur that maps it into the `Parameters` object. Under the GET operation, this is not used and the String content is empty so it's only ever populated at runtime when a POST operation occurs.
Currently writing unit tests.

MAINT-1353 - Added support for POST operation on ValueSet Expansion.

---

kubernetes/snowstorm-deploy.yml

`java -jar snowstorm.jar` is already part of the `ENTRYPOINT` of the container.

Fix Kubernetes config

---

src/main/java/org/snomed/snowstorm/core/data/domain/CodeSystemVersion.java
src/main/java/org/snomed/snowstorm/core/data/services/BranchMetadataKeys.java
src/main/java/org/snomed/snowstorm/core/data/services/CodeSystemService.java
src/main/java/org/snomed/snowstorm/core/data/services/CodeSystemUpgradeService.java
src/main/java/org/snomed/snowstorm/rest/CodeSystemController.java
src/test/java/org/snomed/snowstorm/core/data/services/CodeSystemServiceIntegrationTest.java

@kaicode  Please review my changes for this. I have updated the API parameters after our discussion. However I have decided to leave the metadata updating logic out for now when creating a new code system. Because Dev-ops still need to run the metadata update for other configs.

Maint 1346

---

src/main/java/org/snomed/snowstorm/core/data/domain/SnomedComponent.java
src/main/java/org/snomed/snowstorm/core/data/services/BranchMergeService.java
src/main/java/org/snomed/snowstorm/core/data/services/ConceptService.java
src/main/java/org/snomed/snowstorm/core/data/services/ConceptUpdateHelper.java
src/main/java/org/snomed/snowstorm/core/data/services/ReferenceSetMemberService.java
src/test/java/org/snomed/snowstorm/commitexplorer/CommitExplorer.java
src/test/java/org/snomed/snowstorm/core/data/services/BranchMergeServiceTest.java

Scenario for MAINT-1323 is that a concept is versioned on MAIN and also edited on some task.   The versioned concept is rebased to the project and the task is promoted, causing a merge conflict.    The user selects the right hand side and, during the merge, the "existing" concept that is used to copy the "release details" is taken from the task branch.  The details relating to versioning are then lost.     This code fix additionally collects the existing concepts from the _source_ branch (in this case the project) and pulls the release details from there **if** a concept has been released when the task version of the concept has not been.

MAINT-1323 Fix concepts losing release details

---

src/main/java/org/snomed/snowstorm/rest/pojo/ConceptBulkLoadRequest.java
src/test/java/org/snomed/snowstorm/rest/ConceptControllerTest.java

MAINT-1372 is concerned with fixing a bug in Snowstorm where the "No value specified for terms query" message appears in the log. 
To reproduce this bug, send a POST request to the _concepts/bulk-load_ endpoint with null Concept identifiers; the request will fail. The request will fail because the queryBuilder (ConceptService, line 359) will attempt to build a query with an invalid (null) terms query. 
To fix this bug, I am ignoring all null identifiers (by deserialising with setConceptIdsSafely).

MAINT-1372 Fix Snowstorm Log error "No value specified for terms query"

---

src/main/java/org/snomed/snowstorm/core/data/services/identifier/IdentifierCacheManager.java
src/test/java/org/snomed/snowstorm/core/data/services/identifier/IdentifierCacheManagerTest.java

MAINT-1572 is concerned with reducing Concept save time by prefetching SCTIDs for non-International namespaces.

MAINT-1572 Reduce Concept save time

---

src/main/java/org/snomed/snowstorm/core/data/services/ConceptAttributeSortHelper.java
src/main/java/org/snomed/snowstorm/core/data/services/classification/ClassificationService.java

MAINT-1624 is concerned with updating the Classification's before/after view such that it is the same as the editing view panel.

MAINT-1624 Sort Relationships before responding with Concept preview

---

pom.xml
src/main/java/org/snomed/snowstorm/config/ElasticsearchConfig.java
src/main/java/org/snomed/snowstorm/config/aws/AWSRequestSigningApacheInterceptor.java

amazon-archives/aws-request-signing-apache-interceptor#8
This change hasn't been published to the maven repository, which seems to not be maintained by anyone anymore. https://mvnrepository.com/artifact/com.github.awslabs/aws-request-signing-apache-interceptor/deb7941e85
amazon-archives/aws-request-signing-apache-interceptor#2
Props to Amazon for not including this in their java sdk 😅
I am not entirely sure if it's preferable to have this interceptor in this repository, but the alternatives are to try to find someone who maintains this dependency in a public repository, with no guarantees that he will keep maintaining this.

Fix AWS signing with empty request entity

---

src/main/java/org/snomed/snowstorm/fhir/services/FHIRHelper.java
src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProvider.java
src/main/java/org/snomed/snowstorm/fhir/services/HapiParametersMapper.java
src/main/java/org/snomed/snowstorm/fhir/services/HapiValueSetMapper.java
src/test/java/org/snomed/snowstorm/fhir/services/AbstractFHIRTest.java
src/test/java/org/snomed/snowstorm/fhir/services/CodeSystemProviderLookupTest.java

MAINT-1030 is concerned with updating the response for both CodeSystem $lookup and ValueSet $expand to include the Concept's active state.

MAINT-1030 FHIR: Set inactive flag by default when concept is inactive

---

src/main/java/org/snomed/snowstorm/SnowstormApplication.java
src/main/java/org/snomed/snowstorm/core/data/domain/CodeSystemVersion.java
src/main/java/org/snomed/snowstorm/core/data/domain/jobs/ExportConfiguration.java
src/main/java/org/snomed/snowstorm/core/data/services/CodeSystemService.java
src/main/java/org/snomed/snowstorm/core/data/services/CodeSystemVersionService.java
src/main/java/org/snomed/snowstorm/core/rf2/export/ExportService.java
src/main/java/org/snomed/snowstorm/rest/CodeSystemController.java
src/main/java/org/snomed/snowstorm/rest/pojo/ItemsPage.java
src/test/java/org/snomed/snowstorm/core/rf2/export/ExportServiceTest.java
src/test/java/org/snomed/snowstorm/rest/CodeSystemControllerTest.java

MAINT-1268 is concerned with updating the `CodeSystemController` to return an additional `dependantVersionEffectiveTime` property to indicate which specific version of SCT the `CodeSystemVersion` depends on.

MAINT-1268 Show CodeSystemVersion.dependantVersionEffectiveTime when viewing CodeSystem

---

src/main/java/org/snomed/snowstorm/rest/ControllerHelper.java
src/test/java/org/snomed/snowstorm/rest/ConceptControllerTest.java

BROWSE-436 is concerned with updating Snowstorm to allow optional whitespace in the Accept-Language HTTP header. This was originally raised as a [GitHub Issue](https://github.com/IHTSDO/snowstorm/issues/278).

BROWSE-436 Allow whitespace in Accept-Language HTTP header

---

src/main/java/org/snomed/snowstorm/core/data/services/DescriptionService.java

Minor change to allow multisearch/referencesets to take descriptionId as a parameter.

RT2-153: Multisearch return refset buckets given descriptionId parameter

---

src/main/java/org/snomed/snowstorm/core/data/services/servicehook/CommitInformation.java
src/test/java/org/snomed/snowstorm/core/data/services/servicehook/CommitInformationTest.java

FRI-54 is concerned with either allowing or disallowing a project promotion depending on whether the appropriate criteria have been completed. The previous PR related to FRI-54 submitted was not fully tested and had a slight oversight.
Currently, when Snowstorm is promoting, the _target_ branch will be sent to AAG for criteria verification rather than the _source_ branch.

FRI-54 Change CommitInformation to have source & target branch paths

---

src/main/java/org/snomed/snowstorm/rest/ConceptController.java

As requested previously, changed the optional parameter to default to null, but had missed updating the .equals() call lower down.  Fixing.

Resolving NPE

---

src/main/java/org/snomed/snowstorm/core/data/services/servicehook/CommitServiceHookClient.java

FRI-54 is concerned with blocking promotion if the AAG indicates the associated criteria for a branch has not been completed. 
A flag has previously been added (`blockPromotion`) to toggle whether promotions should be blocked if the criteria has not been completed. This PR also adds another property (`failIfError`) to toggle whether promotions should be blocked if Snowstorm cannot communicate with AAG.

FRI-54 Add another property to toggle whether promotions should be blocked

---

src/main/java/org/snomed/snowstorm/core/data/services/classification/ClassificationService.java

FRI-123 is concerned with updating the PAC/SAC classification criteria on AAG whenever a commit is made. 
The majority of the functionality was written in FRI-61; this PR simply adds support for an edge case where the classification results are empty (as this does not trigger a commit).

FRI-123 Update classification PAC/SAC automatically

---

src/main/java/org/snomed/snowstorm/core/data/services/BranchMetadataHelper.java
src/main/java/org/snomed/snowstorm/rest/BranchController.java
src/main/java/org/snomed/snowstorm/rest/pojo/SetAuthorFlag.java
src/test/java/org/snomed/snowstorm/rest/AbstractControllerSecurityTest.java
src/test/java/org/snomed/snowstorm/rest/BranchControllerTest.java

FRI-182 is concerned with adding functionality to allow flags to be associated with Criteria Items.
This feature relies on feature/FRI-182 of AAG.

FRI-182 Add setAuthorFlag endpoint

---

src/main/java/org/snomed/snowstorm/core/data/services/ReferenceSetMemberService.java
src/main/java/org/snomed/snowstorm/core/data/services/RefsetDescriptorUpdaterService.java
src/test/java/org/snomed/snowstorm/core/data/services/RefsetDescriptorUpdaterServiceTest.java

FRI-262 is concerned with automatically keeping the refset descriptor refset up to date whenever a refset concept is created/deleted.
There is currently a bug where duplicate reference set members are being created whenever the reference set concept is modified. This PR addresses that issue.

FRI-262 Prevent duplicates being written to descriptor refset

---

src/main/java/org/snomed/snowstorm/fhir/services/HapiParametersMapper.java
src/main/java/org/snomed/snowstorm/fhir/services/HapiValueSetMapper.java
src/test/java/org/snomed/snowstorm/fhir/services/ValueSetProviderEclTest.java

Raised on behalf of @danka74 (originally #307)
"First attempt at implementing DUC FHIR extension: https://confluence.ihtsdotools.org/display/FHIR/Designation+extension
There are some things to discuss, e.g. how to turn this on or off or otherwise control the use of the extension.
Also, only added this for ValueSet expansion and not for CodeSystem lookup (but should be similar)."

Designation use context FHIR extension implementation

---

src/main/java/org/snomed/snowstorm/core/data/services/classification/ClassificationService.java
src/main/java/org/snomed/snowstorm/core/data/services/classification/ClassificationStatusService.java
src/main/java/org/snomed/snowstorm/core/data/services/classification/JMSListenerClassificationStatusService.java
src/main/java/org/snomed/snowstorm/core/data/services/classification/RemoteClassificationServiceClient.java
src/main/java/org/snomed/snowstorm/core/data/services/classification/RestTemplateClassificationStatusService.java
src/main/java/org/snomed/snowstorm/core/data/services/classification/pojo/ClassificationStatusResponse.java
src/main/resources/application.properties

FRI-27 is concerned with updating Snowstorm to retrieve a Classification's status via JMS instead of HTTP.
This PR changes Snowstorm to request Classifications be written to a new queue and to listen to the new queue for Classification status updates.

FRI-27 Consume Classification status via JMS

---

src/main/java/org/snomed/snowstorm/core/data/services/SBranchService.java
src/main/java/org/snomed/snowstorm/dailybuild/DailyBuildService.java
src/test/java/org/snomed/snowstorm/dailybuild/DailyBuildServiceTest.java

This fixes the case where somehow the branch documents since the last versioning commit are larger than 100MB. The fix filters the fields of the branch documents when loading a page of them then loads them one by one after filtering so that the 100MB limit is not triggered.

Fix #352 dailybuild rollback error when large number of versionsreplaced

---

CHANGELOG.md
src/main/java/org/snomed/snowstorm/rest/ConceptController.java

Controller unit tests still pass.
Local manual tests look good:
Search after still works.

Fixes #367 return concept ids as strings when returnIdOnly param used.

---

src/main/java/org/snomed/snowstorm/core/data/domain/CodeSystem.java
src/main/java/org/snomed/snowstorm/dailybuild/DailyBuildService.java
src/main/java/org/snomed/snowstorm/rest/CodeSystemController.java

Aim of the pull request is to make it more obvious for users how to find the latest db. Current ways of inspecting branches or checking authoring stats doesn't give a simple answer to the questions: has the db been loaded today, and if so, which version has Snowstorm loaded?
Two things here:
1. Added a property to codesystems: latestDailyBuild
2. A small endpoint which only checks latestDailyBuild against today's date. Obviously, this isn't a 'necessary' endpoint to add. The rationale behind it was to move that logic from the client to Snowstorm to enable users to use simpler alerts/notification tools (or for non-technical users who cannot define that logic themselves) for triggering a failed db alert.

Add property latestDailyBuild

---

src/main/java/org/snomed/snowstorm/core/data/services/SemanticIndexUpdateService.java
src/test/java/org/snomed/snowstorm/core/data/services/SemanticIndexUpdateServiceTest.java

From ticket:
> We would like to exclude the MRCM refsets from the IPS terminology.
>
> The MRCM refsets are currently required by the ECL index service within Snowstorm to check the data type of the concrete values being indexed.
>
> Try to update the Snowstorm import and ECL index service to work without the MRCM by guessing the data type. All numbers could be indexed as decimals because "=#1" and "=#1.0" are treated the same in ECL anyway.
> 
> This will allow us to exclude the MRCM refsets from the IPS and other future subontologies / terminology products.
This pull request stops the RF2 import from failing when the MRCM is missing. Number concrete domains will default to decimal data type if missing from the MRCM. ECL requests still work as expected as shown in unit tests.

MAINT-1882 Snowstorm IPS Import without MRCM

---

src/main/java/org/snomed/snowstorm/rest/ControllerHelper.java
src/main/resources/application.properties

When providing just a 2-character language tag with Accept-language (no refset or dialect), the language reference set selected (and the PT provided by snowstorm) becomes slightly random. The PT provided will be any preferred term in any lanugage reference set in the order they are provided.
By adding the default language reference set under "# SNOMED Known Dialects - Individual Configuration" in the application.properties file and adding this default lanugage reference set when a 2-character Accept-language header is given, the assigning of PT becomes predictable.

default lang refset for lang only accept header

---

src/main/java/org/snomed/snowstorm/core/data/domain/Concepts.java
src/main/java/org/snomed/snowstorm/core/data/services/BranchReviewService.java
src/main/java/org/snomed/snowstorm/core/data/services/ConceptUpdateHelper.java
src/test/java/org/snomed/snowstorm/core/data/services/BranchMergeServiceTest.java

FRI-210 is concerned with preventing International changes being lost whenever an Extension does an upgrade/a rebase.

FRI-210 Preserve International changes after Extension upgrade

---

src/main/java/org/snomed/snowstorm/dailybuild/DailyBuildService.java
src/main/java/org/snomed/snowstorm/rest/CodeSystemController.java

endpoint makes it easier for us to test, debug and/or reactivate DB after a rollback, an upgrade or similar situation where I want to remove the DB and not have to wait X minutes or change the config file and restart the app twice.

Endpoint to trigger scheduled dailybuild import

---

pom.xml
src/main/java/org/snomed/snowstorm/ecl/BranchVersionECLCache.java
src/main/java/org/snomed/snowstorm/ecl/ECLContentService.java
src/main/java/org/snomed/snowstorm/ecl/SECLObjectFactory.java
src/main/java/org/snomed/snowstorm/ecl/domain/expressionconstraint/SSubExpressionConstraint.java
src/main/java/org/snomed/snowstorm/ecl/domain/filter/ECLToStringUtil.java
src/main/java/org/snomed/snowstorm/ecl/domain/filter/SDescriptionFilterConstraint.java
src/main/java/org/snomed/snowstorm/ecl/domain/filter/SEffectiveTimeFilter.java
src/main/java/org/snomed/snowstorm/ecl/domain/filter/SFieldFilter.java
src/main/java/org/snomed/snowstorm/ecl/domain/filter/SMemberFieldFilter.java
src/main/java/org/snomed/snowstorm/ecl/domain/filter/STermFilter.java
src/test/java/org/snomed/snowstorm/ecl/BranchVersionECLCacheTest.java
src/test/java/org/snomed/snowstorm/ecl/ECLQueryServiceFilterTest.java
src/test/java/org/snomed/snowstorm/ecl/ECLQueryServiceFilterTestConfig.java
src/test/java/org/snomed/snowstorm/ecl/deserializer/ECLModelDeserializerServiceTest.java
src/test/resources/application-test.properties

In the UAT environment these ECL queries are giving the same results.
<< 195967001 |Asthma| {{ D active = 0 }}
<< 195967001 |Asthma| {{ D active = 1 }}
> After investigation I found that this is caused by an ECL cache bug.
ECL is converted from Java objects back into text for the ECL cache lookup. This issue was that some of the description filters were not being included in the text when converted.
> I have now added [unit tests covering the conversion of all filter types](https://github.com/IHTSDO/snowstorm/blob/6d9bd593352277d80f5e3e1f373ecf601835e4c0/src/test/java/org/snomed/snowstorm/ecl/deserializer/ECLModelDeserializerServiceTest.java#L198) for all component types and fixed all remaining issues in this area. I found that the description module, effectiveTime and active filters were …

ISTO-42 Fix ECL caching bug

---

pom.xml

Hi @CoderMChu,
I was not able to run unit tests on the develop branch in IDEA. I think this was due to some inconsistencies in the unit test libraries we were using. I've upgraded the test containers to latest and remove the forced old version of jupiter. This seems to have resolved the issue. If this looks good to you please merge to dev.
Kai

MAINT-1921 Make test library versions consistent.

---

docs/configuration-guide.md

Replace --spring.config.location with non-replacing --spring.config.additional-location.
https://docs.spring.io/spring-boot/docs/current/reference/html/application-properties.html#application-properties.core.spring.config.additional-location
Addresses #366

spring.config.additional-location

---

src/main/java/org/snomed/snowstorm/core/data/services/traceability/Activity.java
src/main/java/org/snomed/snowstorm/core/data/services/traceability/TraceabilityConsumer.java
src/main/resources/application.properties
src/test/java/org/snomed/snowstorm/core/data/services/traceability/TraceabilityConsumerTest.java

I opened a new PR because the other branch had some persistent git conflicts.
The idea is to send the activities in small batches (size set through a property) and store them as such in the traceability backend (no change required there, no re-assembling)

FRI-443 Batch processing N concept changes per JMS message

---

src/main/java/org/snomed/snowstorm/core/data/services/ReferenceSetMemberService.java
src/main/resources/application.properties

Added a config option for setting up reference set types on other branches than MAIN, which was hardcoded before.
Thought of loading all available branches during app init and config all refset types to all there and then, but this should be good enough for our needs. 
`"refsets.branch"` defaults to MAIN if it's unset in application.properties. If configured branch don't exist exception is thrown (`java.lang.IllegalArgumentException: Branch 'BLABLA' does not exist.`) and app fails to start.

MAINT-1974 Added configurable branch to refset types

---

src/main/java/org/snomed/snowstorm/core/data/services/ConceptUpdateHelper.java
src/test/java/org/snomed/snowstorm/core/data/services/BranchMergeServiceTest.java

The purpose of MAINT-1940 is to prevent inactive historical associations switching module when rebasing with a merge conflict.

MAINT-1940 - Prevent inactive historical associations switching module

---

src/main/java/org/snomed/snowstorm/core/data/services/MultiSearchService.java

We discovered today that the ECL parameter we had added to MultiSearchService.findDescriptions() was no longer functioning after rebasing from develop, due to the multiple changes in the MultiSearchService and in the ECLQueryService.

RT2-1505 - attempt to get multisearch ECL working again.

---

src/main/java/org/snomed/snowstorm/core/data/services/ConceptService.java
src/test/java/org/snomed/snowstorm/rest/ConceptControllerTest.java

Add active flag to the axiom and inferred relationship targets in the browser concept JSON response. This makes it easier to spot when a relationship points to an inactive concept.

ISTO-54 Fixes #426 return target active flag.

---

pom.xml

This PR upgrades Snowstorm to the release version of the HAPI FHIR library in preparation for UAT.
This release jar was built by our Jenkins server and is in our nexus repo.
https://nexus3.ihtsdotools.org/service/rest/repository/browse/maven-releases/ca/uhn/hapi/fhir/hapi-fhir-server/5.6.3-si/

MAINT-2064 Upgrade HAPI FHIR to SI release version

---

src/main/java/org/snomed/snowstorm/core/data/services/MultiSearchService.java
src/main/java/org/snomed/snowstorm/rest/MultiSearchController.java
src/main/java/org/snomed/snowstorm/rest/pojo/MultibranchDescriptionSearchRequest.java
src/test/java/org/snomed/snowstorm/core/data/services/MultiSearchServiceTest.java

The intention is to allow users to specify additional, non-published branches to include in the search.  This will be used by RT2 to search refset names across all branches, and can potentially be useful to other others as well.

RT2-1567: Creating POST version of multisearch findDescriptions 

---

src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java
src/main/java/org/snomed/snowstorm/fhir/services/HapiParametersMapper.java
src/test/java/org/snomed/snowstorm/fhir/services/FHIRCodeSystemProviderLookupTest.java
src/test/java/org/snomed/snowstorm/fhir/services/FHIRCodeSystemProviderValidateTest.java
src/test/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProviderExpandEclTest.java
src/test/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProviderExpandTest.java

This PR contains various fixes for the Snowstorm FHIR interface relating to the inactive flag.
- Fixed ValueSet $expand
- inactive flag was inverted)
- Fixed CodeSystem $lookup
- Added "inactive" property to conform with standard
- Removed "active" property because redundant
- Added "inactive" property to CodeSystem $validate-code
- Added "inactive" property to ValueSet $validate-code

ISTO-94 Snowstorm FHIR Inctive Flag

---

src/main/java/org/snomed/snowstorm/core/data/services/ConceptUpdateHelper.java
src/test/java/org/snomed/snowstorm/core/data/services/ConceptServiceTest.java

This is a bug fix to set the module for description inactivation indicators on new descriptions on already inactive concepts. Before this fix the module was blank.

ISTO-97 defaultModule for desc inactivation indicator

---

src/main/java/org/snomed/snowstorm/config/Config.java
src/main/java/org/snomed/snowstorm/core/rf2/rf2import/ImportService.java
src/test/java/org/snomed/snowstorm/core/rf2/rf2import/ImportServiceTest.java

This PR stops anyone using the FULL import on branches other than MAIN. The branch also needs to be empty. This block should have been there from the start because all content is imported against the current parent code system version, this is incorrect behaviour.
A complete child Edition/Extension import feature could be implemented in the future.

ISTO-95 Block FULL import unless on empty MAIN.

---

src/main/java/org/snomed/snowstorm/fhir/domain/ConceptConstraint.java
src/main/java/org/snomed/snowstorm/fhir/services/CodeSelectionCriteria.java
src/main/java/org/snomed/snowstorm/fhir/services/FHIRTermCodeSystemStorage.java
src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java

These commits fix the LOINC package loading issues. The changes are:
- Stop attempting to expand ValueSet resources during import. This was leading to issues when nested value sets were not yet imported.
- When a user expands a value set simplify the Elasticsearch clauses for nested value sets to prevent the clause limit being exceeded for some LOINC sets.

Fix MAINT-2227 - Issues loading LOINC package

---

src/main/java/org/snomed/snowstorm/config/SecurityAndUriConfig.java
src/main/java/org/snomed/snowstorm/core/data/services/ReferenceSetMemberService.java
src/main/java/org/snomed/snowstorm/rest/ReferenceSetMemberController.java
src/main/java/org/snomed/snowstorm/rest/config/ReferenceSetTypeMixin.java
src/main/resources/application.properties

This PR updates the browser member API endpoint to add more details about each refset type. This is required to support generating SNOMED Release Service manifest xml files in the upcoming Simplex Tool.
I have also fixed the Snowstorm refset configuration for the ICD-10 and ICD-9-CM maps. The config now points to the generic Complex Map and Extended Map types rather than any specific refset. This is in line with the rest of the configuration and means that any other maps of these types will also pick up the correct configuration. This area of configuration is the source of the information that is now exposed in the refset API.

ISTO-99 Snowstorm refset member API, add details to support SRS manifest generation

---

src/main/java/org/snomed/snowstorm/core/data/domain/QueryConcept.java
src/test/java/org/snomed/snowstorm/core/data/domain/QueryConceptTest.java
src/test/java/org/snomed/snowstorm/core/data/services/SemanticIndexUpdateServiceTest.java

This fixes the way that decimal numbers are stored in the Snowstorm semantic index, that is used for ECL queries.
Previously concrete domain numbers like `0.00005` were stored in the index in scientific notation like `5.0E-4`. This causes ECL queries that use that number to throw an exception.
Unit tests are included that test:
- the serialisation and deserialisation of this number
- An ECL query using this number that previously failed when the format was bad

MAINT-2384 Fix decimal serialisation in ECL index.

---

src/main/java/org/snomed/snowstorm/rest/DescriptionController.java

In **Descriptions** section, some swagger params names are not working well. I changed _name_ field by _description_.

Documentation: Fix params name in description search Swagger docs

---

docs/using-the-fhir-api.md
src/main/resources/ca/uhn/fhir/jpa/term/loinc/loincupload.properties

This PR adds config that is picked up by the HAPI FHIR library so that the new LOINC zip entry file naming is used, enabling the latest LOINC packages to be loaded.
This change has already been tested today, see jira ticket for details.

ISTO-107 Fix loading LOINC 2.73 and above

---

pom.xml
src/main/java/org/snomed/snowstorm/core/data/domain/QueryConcept.java
src/main/java/org/snomed/snowstorm/core/data/services/BranchMetadataKeys.java
src/main/java/org/snomed/snowstorm/core/data/services/SemanticIndexUpdateService.java
src/main/java/org/snomed/snowstorm/core/data/services/identifier/LocalRandomIdentifierSource.java
src/main/java/org/snomed/snowstorm/core/rf2/rf2import/ImportService.java
src/main/java/org/snomed/snowstorm/dailybuild/DailyBuildService.java
src/test/java/org/snomed/snowstorm/core/data/domain/QueryConceptTest.java
src/test/java/org/snomed/snowstorm/core/data/services/SemanticIndexUpdateServiceTest.java
src/test/java/org/snomed/snowstorm/core/rf2/rf2import/ImportServiceTest.java

MAINT-2403 Update Snowstorm to allow separate semantic index. 
ElasticVC contains most of the changes required for this feature.

MAINT-2403 Update Snowstorm to allow separate semantic index 

---

src/main/java/org/snomed/snowstorm/core/data/services/ReferenceSetMemberService.java

Refset type checks fail gracefully if the MAIN branch is locked during startup.

MAINT-2529 Startup RS type checks fail gracefully.

---

src/main/java/org/snomed/snowstorm/mrcm/MRCMService.java

MRCM type-ahead language fix.
Related to issue #589, ISTO-119 and INFRA-12853.

Fix #589 MRCM search with requested language

---

src/main/java/org/snomed/snowstorm/fhir/services/FHIRConceptService.java
src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java

This fixes a bug in the Snowstorm FHIR API where it's not possible to paginate beyond a 10,000 code offset. 
This regression was introduced during the Elasticsearch 8 upgrade last year. It is caused by the Spring Boot Elasticsearch 8 library not allowing queries to be reused.
Local testing shows that these changes fix the bug. I have also added result sorting based on code to ensure consistent pagination with different page sizes which makes testing easier.
This screenshot shows using a very large offset to a page with the last three LOINC codes:
Performance is quite poor because with Elasticsearch we can not jump to an offset beyond 10k, we have to scroll through the results. The search-after token technique would solve this but it's not compatible with the FHIR API.

Fixes #638 ISTO-125 LOINC pagination fix.

---

pom.xml
src/main/java/org/snomed/snowstorm/core/data/services/DescriptionService.java
src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetService.java
src/test/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProviderExpandGenericTest.java

Two bugs have been created related to the LOINC CodeSystem within the Snowstorm FHIR API.
The first bug is a regression. No LOINC version can be imported into Snowstorm version 10.5.1 because of a library version mismatch.
https://github.com/IHTSDO/snowstorm/issues/642
The second bug is related to search within LOINC. It's only possible to search using one word or word prefix. When using two or more words or prefixes Snowstorm never matches anything. This is a major usability issue. 
https://github.com/IHTSDO/snowstorm/issues/641
Both of these bugs can be fixed easily and only relate to the FHIR API which is not used anywhere within the Authoring Platform. The FHIR API is hosted by Snowstorm as part of the public browser server although we do not import the native LOINC package there.

Loinc fixes PR - ISTO-127
