- Dockerfile
- kubernetes/Readme.md
- kubernetes/ingress-rules.yml
- kubernetes/snowstorm-deploy.yml
Hi Snomed,
We have done some test with your develop branch:
- Fix Dockerfiles (Missing directory + add maintainer label)
- Kubernetes deployment of snowstorm inside of Kubernetes
- Add a little Readme as a how-to.
Please let me know if it's helpful.
Regards,
Zwordi
>  Fix Dockerfiles for missing directory inside docker + Kubernetes Deployment example.

- README.md
- docs/updating-snomed-and-extensions.md
- kubernetes/Readme.md
- pom.xml
Changes to the POM primarily for new snomed-boot (see other pull request) and improvements/clarifications in the documentation around extension/edition loading
> Changes to import UK Edition

- src/main/java/org/snomed/snowstorm/core/data/domain/jobs/ExportConfiguration.java
- src/main/java/org/snomed/snowstorm/core/rf2/export/ConceptExportWriter.java
- src/main/java/org/snomed/snowstorm/core/rf2/export/DescriptionExportWriter.java
- src/main/java/org/snomed/snowstorm/core/rf2/export/ExportService.java
- src/main/java/org/snomed/snowstorm/core/rf2/export/ExportWriter.java
- src/main/java/org/snomed/snowstorm/core/rf2/export/ReferenceSetMemberExportWriter.java
- src/main/java/org/snomed/snowstorm/core/rf2/export/RelationshipExportWriter.java
- src/test/java/org/snomed/snowstorm/core/rf2/export/ExportServiceTest.java
Hi Kai,
Can you review my changes please?
Thanks
Michael
> STORM-184: Add transientEffectiveTime option during RF2 export

- src/main/java/org/snomed/snowstorm/fhir/config/HapiRestfulServlet.java
- src/main/java/org/snomed/snowstorm/fhir/services/FHIRMedicationProvider.java
This a new endpoint in the FHIR API (/fhir/Medication) that retrieves a Medication resource created form the definition of a given SNOMED CT Clinical Drug Concept.
> Adding FHIR Medication Resource endpoint

- docs/fhir-requests.http
Updated the validate-code requests to use code instead of coding.
> Coding replaced by code

- pom.xml
- src/main/java/org/snomed/snowstorm/validation/domain/DroolsRelationship.java
- src/test/java/org/snomed/snowstorm/validation/DroolValidationServiceTest.java
- src/test/resources/application-test.properties
- src/test/resources/drool-test-resources/common-authoring/concept-active-state/active-concept-at-least-one-parent/AtLeastOneParent.drl
- src/test/resources/drool-test-resources/common-authoring/concept-active-state/active-concept-at-least-one-parent/test-cases.json
- src/test/resources/drool-test-resources/common-authoring/terms/fsn-semantic-tag-against-parent/FSNSemanticTagAgainstParent.drl
- src/test/resources/drool-test-resources/common-authoring/terms/fsn-semantic-tag-against-parent/test-cases.json
- src/test/resources/drool-test-resources/common-authoring/terms/fsn-term/FSNTermFormat.drl
- src/test/resources/drool-test-resources/common-authoring/terms/fsn-term/test-cases.json
Drools Snowstorm Implementation against Concrete domain value
> CDI-45 Concrete Domains Drools Snowstorm Implementation

- src/main/java/org/snomed/snowstorm/core/data/domain/ConcreteValue.java
- src/test/java/org/snomed/snowstorm/rest/ConceptControllerTest.java
The underlying issue was related to marshalling, as Jackson requires a default no arg constructor and the ConcreteValue did not have one so it was throwing a mapping exception. After adding this default public constructor, the marshalling is performed successfully and the create/update operation work as expected.
> CDI-43 - Concrete values can now be stored within the stated form (axioms) when creating and updating concepts.

- src/main/java/org/snomed/snowstorm/fhir/services/FHIRHelper.java
This now compiles and passes through tests!
It addresses one issue related to https://github.com/IHTSDO/snowstorm/issues/199
> Langref fix

- src/main/java/org/snomed/snowstorm/core/data/domain/jobs/ExportConfiguration.java
- src/main/java/org/snomed/snowstorm/core/rf2/export/ExportService.java
- src/test/java/org/snomed/snowstorm/core/rf2/export/ExportServiceTest.java
Decided to make a new fork and apply changes from scratch because of the white space issues.  I believe I've addressed all of your concerns that were indicated on the initial pull request.
> RT2-56b: refset-only export (redo)

- src/main/java/org/snomed/snowstorm/core/rf2/export/ExportService.java
@shapirod2 would this work as a further simplification to avoid code duplication? The unit tests you added still pass.
> RT2-56 Refset only export refactor / simplification.

- src/main/java/org/snomed/snowstorm/core/data/services/servicehook/CommitServiceHookClient.java
- src/main/resources/application.properties
- src/test/java/org/snomed/snowstorm/AbstractTest.java
- src/test/java/org/snomed/snowstorm/core/data/services/BranchMergeServiceTest.java
- src/test/java/org/snomed/snowstorm/fhir/services/AbstractFHIRTest.java
> Revert "FRI-54 - Request permission for project promotion from AAG"

- pom.xml
To get latest version of KaiCode BranchCriteria
> Upversioning elasticv to 3.1.3

- pom.xml
- src/test/java/org/snomed/snowstorm/TestConfig.java
> Fixes #344 Upgrade test libs and jna to fix unit tests on arm64.

- README.md
- docs/code-systems-and-branches.md
- docs/search.md
Added documentation for the native API
- Code Systems & Branches
- Search Guide
> Documentation update - code systems and search

- pom.xml
Fixes log4j vulnerability issue as raised by Daniel in #347.
> Fixes #347 Log4j vulnerability by upgrading minor versions to latest.

- src/main/java/org/snomed/snowstorm/core/data/services/BranchReviewService.java
- src/main/java/org/snomed/snowstorm/core/data/services/ReferenceSetMemberService.java
- src/test/java/org/snomed/snowstorm/core/data/services/BranchMergeServiceTest.java
- src/test/java/org/snomed/snowstorm/core/data/services/BranchReviewServiceTest.java
FRI-234 is concerned with updating merge to cover scenarios where content is deleted after it has been versioned.
> FRI-234 Silently restore deleted versioned content

- docs/loading-snomed.md
- docs/updating-snomed-and-extensions.md
Added warnings about rollup deltas to the general Loading SNOMED doc.
Updated advice on the extension loading doc about monthly releases and using snapshots. Also updated dates in examples.
> Rollup delta warnings

- src/main/java/org/snomed/snowstorm/core/data/domain/QueryConcept.java
- src/main/java/org/snomed/snowstorm/core/data/services/pojo/MemberSearchRequest.java
- src/main/java/org/snomed/snowstorm/rest/ImportController.java
@CoderMChu I checked the LGTM report and found a couple of issues.
This PR fixes the 2 warnings and 1 recommendation but I'm not sure how best to tackle the 1 error that was raised. Let's talk further.
> MAINT-1968 Fix code quality warnings and recommendation from LGTM report.

- src/main/java/org/snomed/snowstorm/core/data/domain/SnomedComponent.java
- src/main/java/org/snomed/snowstorm/core/data/services/AdminOperationsService.java
- src/main/java/org/snomed/snowstorm/core/data/services/BranchMergeService.java
- src/main/java/org/snomed/snowstorm/core/data/services/DescriptionService.java
- src/main/java/org/snomed/snowstorm/core/data/services/DomainEntityConfiguration.java
- src/main/java/org/snomed/snowstorm/core/data/services/MultiSearchService.java
- src/main/java/org/snomed/snowstorm/core/data/services/ReleaseService.java
- src/main/java/org/snomed/snowstorm/core/data/services/pojo/DescriptionCriteria.java
- src/main/java/org/snomed/snowstorm/core/rf2/rf2import/ImportComponentFactoryImpl.java
- src/main/java/org/snomed/snowstorm/rest/MultiSearchController.java
- src/test/java/org/snomed/snowstorm/core/data/services/MultiSearchServiceTest.java
PR to get RT2 content into the integration branch.
> Rt2 436 for snomed develop

- src/main/java/org/snomed/snowstorm/core/data/services/DescriptionService.java
PR to get RT2 content into the integration branch.
> RT2-153: Multisearch return refset buckets given descriptionId parameter

- src/main/java/org/snomed/snowstorm/core/data/services/QueryService.java
- src/main/java/org/snomed/snowstorm/ecl/ECLQueryService.java
- src/main/java/org/snomed/snowstorm/rest/ConceptController.java
- src/main/java/org/snomed/snowstorm/rest/pojo/ConceptSearchRequest.java
PR to get RT2 content into the integration branch.
> Rt2 126and130and259 for snomed develop

- pom.xml
- src/main/java/org/snomed/snowstorm/core/data/services/CodeSystemUpgradeService.java
- src/main/java/org/snomed/snowstorm/core/data/services/pojo/CodeSystemUpgradeJob.java
- src/main/java/org/snomed/snowstorm/rest/CodeSystemController.java
- src/test/java/org/snomed/snowstorm/core/data/services/BranchMergeServiceTest.java
- src/test/java/org/snomed/snowstorm/core/data/services/CodeSystemServiceIntegrationTest.java
- src/test/java/org/snomed/snowstorm/core/data/services/MultiSearchServiceTest.java
- src/test/java/org/snomed/snowstorm/core/data/services/TraceabilityLogServiceTest.java
- src/test/java/org/snomed/snowstorm/dailybuild/DailyBuildServiceTest.java
- src/test/java/org/snomed/snowstorm/rest/CodeSystemControllerSecurityTest.java
- src/test/java/org/snomed/snowstorm/rest/CodeSystemControllerTest.java
Rename debian package "snowstorm-integration" for integration branch.
> Integration snowstorm fix

- src/deb/supervisor.conf
Update supervisor.conf to address debian deploy failures
> Update supervisor.conf to address debian deploy failures

- src/main/java/org/snomed/snowstorm/fhir/services/FHIRCodeSystemProvider.java
- src/main/java/org/snomed/snowstorm/fhir/services/FHIRHelper.java
- src/main/java/org/snomed/snowstorm/fhir/services/FHIRStructureDefinitionProvider.java
- src/main/java/org/snomed/snowstorm/fhir/services/FHIRValueSetProvider.java
See https://jira.ihtsdotools.org/browse/ISTO-79
> ISTO-79 FHIR: Read-only mode blocks CRUD operations.

- src/main/java/org/snomed/snowstorm/core/data/domain/CodeSystemVersion.java
- src/main/java/org/snomed/snowstorm/core/data/domain/review/MergeReviewConceptVersions.java
- src/main/java/org/snomed/snowstorm/core/data/services/BranchReviewService.java
- src/main/java/org/snomed/snowstorm/core/data/services/CodeSystemService.java
- src/main/java/org/snomed/snowstorm/core/data/services/SBranchService.java
- src/test/java/org/snomed/snowstorm/core/data/services/BranchMergeServiceTest.java
FRI-600 is concerned with indicating whether the RHS of the conflict window is a version behind, i.e. the LHS is February 2023 but the RHS is January 2023.
> FRI-600 Indicate whether RHS of conflict window is version behind

- docs/loading-snomed.md
- src/main/java/org/snomed/snowstorm/core/data/services/CodeSystemService.java
- src/main/java/org/snomed/snowstorm/fix/TechnicalFixService.java
- src/main/java/org/snomed/snowstorm/fix/TechnicalFixType.java
- src/main/java/org/snomed/snowstorm/rest/AdminController.java
- src/main/java/org/snomed/snowstorm/rest/pojo/ResponseMessage.java
@CoderMChu  Could you merge this to develop please?
See conversation on the ticket with RDA.
> ISTO-30 Snowstorm Admin Function to Create Empty Release as Subontology Dependency

- src/main/java/org/snomed/snowstorm/core/data/services/MultiSearchService.java
- src/main/java/org/snomed/snowstorm/core/data/services/pojo/DescriptionCriteria.java
- src/main/java/org/snomed/snowstorm/rest/MultiSearchController.java
- src/main/java/org/snomed/snowstorm/rest/pojo/MultibranchDescriptionSearchRequest.java
- src/test/java/org/snomed/snowstorm/core/data/services/MultiSearchServiceTest.java
RT2 changes to re-add Creating POST version of multisearch  findDescriptions
> RT2 changes to re-add Creating POST version of multisearch 

- src/main/java/org/snomed/snowstorm/core/data/services/QueryService.java
- src/main/java/org/snomed/snowstorm/ecl/ECLQueryService.java
- src/main/java/org/snomed/snowstorm/rest/ConceptController.java
- src/main/java/org/snomed/snowstorm/rest/pojo/ConceptSearchRequest.java
Adding RT2-specific snowstorm content that was found to be missing from integration.
> Rt2 126and130and259 for snomed integration

- src/main/java/org/snomed/snowstorm/core/data/services/DescriptionService.java
- src/main/java/org/snomed/snowstorm/core/data/services/MultiSearchService.java
- src/main/java/org/snomed/snowstorm/core/data/services/QueryService.java
- src/main/java/org/snomed/snowstorm/core/data/services/pojo/MultiSearchDescriptionCriteria.java
- src/main/java/org/snomed/snowstorm/ecl/ECLQueryService.java
- src/main/java/org/snomed/snowstorm/rest/ConceptController.java
- src/main/java/org/snomed/snowstorm/rest/MultiSearchController.java
- src/main/java/org/snomed/snowstorm/rest/pojo/ConceptSearchRequest.java
- src/main/java/org/snomed/snowstorm/rest/pojo/MultibranchDescriptionSearchRequest.java
- src/test/java/org/snomed/snowstorm/core/data/services/MultiSearchServiceTest.java
RT2-126: Taxonomy Search
RT2-130: Identify Descendants for Taxonomy
RT2-153: Add DescriptionId to reference set search
RT2-259: Add 'leafFlagForm' to concepts search
RT2-436: Modify Refset Multisearch to include the refset's own descriptions
> RT2-required changes to snowstorm

- src/main/java/org/snomed/snowstorm/core/data/domain/jobs/ExportConfiguration.java
- src/main/java/org/snomed/snowstorm/core/data/domain/jobs/ExportStatus.java
- src/main/java/org/snomed/snowstorm/core/rf2/export/ExportService.java
- src/main/java/org/snomed/snowstorm/rest/ExportController.java
PIP-333 is concerned with adding the ability for the UI to download an RF2 export without timing out. To do this, I have added two things:
- Status to ExportConfiguration for polling
- Option to export archive locally
> PIP-333 Add ability to locally persist export

- src/main/java/org/snomed/snowstorm/rest/config/RestControllerAdvice.java
This PR adds proper error handling when static files like web page icons are not found in Snowstorm.
> Fix ISTO-129 #648 Suppress not found error.

- src/main/resources/application.properties
This PR adds the correct default config for the CZ codesystem.
> Add CZ to Snowstorm default configuration
